version: "2"
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "build/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "src/model/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
