name: Test & Coverage
on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:
    paths:
      - '!*.MD'
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '16' ]
    name: test
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm run build
    - run: npm run test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '16'
    - run: npm install
    - run: npm run build
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: npm run coverage
